openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'finances'
servers:
  - url: 'localhost:3000'
paths:
  /incomes:
    get:
      summary: 'Sample endpoint: Returns income details'
      operationId: listIncomes
      tags:
        - income
      parameters:
        - name: id
          in: query
          description: ID of the income
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'OK'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Income'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Income:
      type: object
      properties:
        id:
          type: integer
          format: int64
        descricao:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []