# =================================
# = Spring
# =================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: -------------?&serverTimezone=UTC&useSSL=false
    username: admin
